import "../styles/globals.css";
import "../styles/custom.css";
import { Toaster } from "react-hot-toast";
import DefaultColors from "@/components/atoms/DefaultColors";

export const metadata = {
	title: "Welcome to Neotask",
	description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<div id="modal"></div>
				<DefaultColors>{children}</DefaultColors>
				<Toaster />
			</body>
		</html>
	);
}
