import "../styles/globals.css";
import "../styles/custom.css";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: 'Welcome to Neotask',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        {children}
        <Toaster/>
      </body>
    </html>
  )
}
